CREATE TABLE IF NOT EXISTS blips (
    id INT AUTO_INCREMENT PRIMARY KEY,
    x FLOAT NOT NULL,
    y FLOAT NOT NULL,
    z FLOAT NOT NULL,
    sprite INT NOT NULL DEFAULT 280,
    color INT NOT NULL DEFAULT 2,
    scale FLOAT NOT NULL DEFAULT 0.9,
    name VARCHAR(50) NOT NULL
);
